name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies and build
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env
          bun install --production --frozen-lockfile
          bun -b run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
